repos:
- repo: https://github.com/gherynos/pre-commit-java
  rev: v0.2.16
  hooks:
    - id: pmd
      args: ["-R", "src/main/resources/pmdrules.xml"]
    - id: checkstyle
      args: ["-c", "src/main/resources/checkstyle.xml"]