name: Run check task
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '19'
      - name: Run check
        run: ./gradlew check